// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnajxcvvlubbjmrrgiju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuYWp4Y3Z2bHViYmptcnJnaWp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5MjM4MjcsImV4cCI6MjA1MDQ5OTgyN30.dmMvxuYpVxsSZ9CRYdg__QQy7QLK6JJWp-LfshtJ6S0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);